module.exports = {
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:import/typescript',
    'plugin:prettier/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    parser: '@typescript-eslint/parser',
    extraFileExtensions: ['.cjs', '.mjs', '.cts', '.mts'],
    project: './tsconfig.json',
  },
  rules: {
    'constructor-super': 'off',
    'getter-return': 'off',
    'no-const-assign': 'off',
    'no-dupe-args': 'off',
    'no-dupe-class-members': 'off',
    'no-dupe-keys': 'off',
    'no-func-assign': 'off',
    'no-import-assign': 'off',
    'no-new-symbol': 'off',
    'no-obj-calls': 'off',
    'no-redeclare': 'off',
    'no-setter-return': 'off',
    'no-this-before-super': 'off',
    'no-undef': 'off',
    'no-unreachable': 'off',
    'no-unsafe-negation': 'off',
    'no-var': 'error',
    'prefer-const': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'valid-typeof': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    'import/named': 'off',
    'import/no-named-as-default-member': 'off',
  },
  settings: {
    'import/extensions': ['.js', '.cjs', '.mjs', '.jsx', '.ts', '.cts', '.mts', '.tsx', '.d.ts'],
    'import/parsers': {
      '@typescript-eslint/parser': ['.cts', '.mts', '.ts', '.tsx', '.d.ts'],
    },
    'import/resolver': {
      node: {
        extensions: [
          '.mjs',
          '.js',
          '.cjs',
          '.jsx',
          '.json',
          '.mts',
          '.ts',
          '.cts',
          '.tsx',
          '.d.ts',
        ],
      },
      typescript: {},
    },
  },
};
